#pragma STDC FP_CONTRACT ON
;
#pragma STDC FP_CONTRACT OFF
;
#pragma STDC FP_CONTRACT DEFAULT
;
#pragma STDC FENV_ACCESS ON
;
#pragma STDC FENV_ACCESS OFF
;
#pragma STDC FENV_ACCESS DEFAULT
;
#pragma STDC CX_LIMITED_RANGE ON
;
#pragma STDC CX_LIMITED_RANGE OFF
;
#pragma STDC CX_LIMITED_RANGE DEFAULT