# Generated — clause 6.3 (Conversions). Tests assert ISO C17; partial/unsupported
# rows EXPECTED TO FAIL (conformance signal). Regenerated; do not hand-edit.

add_standard_run_test(lang-6.3.1.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.1_conversion_rank_observable.c supported)
add_standard_run_test(lang-6.3.1.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.1_integer_promotions.c supported)
add_standard_static_assert(lang-6.3.1.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.1_plain_char_signedness.c supported)
add_standard_run_test(lang-6.3.1.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.2_scalar_to_bool.c supported)
add_standard_run_test(lang-6.3.1.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.3_int_to_int_in_range_preserves.c supported)
add_standard_run_test(lang-6.3.1.3-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.3_to_signed_unrepresentable_impl_defined.c supported)
add_standard_run_test(lang-6.3.1.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.3_to_unsigned_wraps_modulo.c supported)
add_standard_run_test(lang-6.3.1.4-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.4_float_to_int_truncates_toward_zero.c supported)
add_standard_run_test(lang-6.3.1.4-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.4_int_to_float_exact_when_representable.c supported)
add_standard_run_test(lang-6.3.1.5-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.5_double_to_float_round_nearest.c supported)
add_standard_run_test(lang-6.3.1.8-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.8_uac_float_operand_wins.c by-design)
add_standard_run_test(lang-6.3.1.8-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.8_uac_otherwise_unsigned_of_signed.c supported)
add_standard_run_test(lang-6.3.1.8-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.8_uac_same_signedness_greater_rank.c supported)
add_standard_run_test(lang-6.3.1.8-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.8_uac_signed_holds_all_unsigned.c supported)
add_standard_run_test(lang-6.3.1.8-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.1.8_uac_unsigned_rank_ge_signed.c supported)
add_standard_run_test(lang-6.3.2.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.1_array_to_pointer_decay.c supported)
add_standard_run_test(lang-6.3.2.1-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.1_function_to_pointer_decay.c supported)
add_standard_run_test(lang-6.3.2.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.1_lvalue_conversion_yields_value.c supported)
add_standard_compile_fail(lang-6.3.2.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.1_nonmodifiable_lvalue_assignment_rejected.c supported)
add_standard_compile_fail(lang-6.3.2.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.2_void_value_cannot_be_used.c supported)
add_standard_run_test(lang-6.3.2.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_add_qualifier_preserves_value.c supported)
add_standard_run_test(lang-6.3.2.3-09 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_function_pointer_roundtrip.c supported)
add_standard_run_test(lang-6.3.2.3-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_integer_to_pointer.c supported)
add_standard_run_test(lang-6.3.2.3-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_null_pointer_constant.c supported)
add_standard_run_test(lang-6.3.2.3-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_null_pointers_compare_equal.c supported)
add_standard_run_test(lang-6.3.2.3-07 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_object_pointer_reinterpret_char.c supported)
add_standard_run_test(lang-6.3.2.3-06 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_pointer_to_integer.c supported)
add_standard_run_test(lang-6.3.2.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.3_conversions/6.3.2.3_voidptr_object_pointer_roundtrip.c supported)
