# Generated — language remainder (Clauses 4, 5, 6.6-6.11). Tests assert ISO C17;
# partial/unsupported rows EXPECTED TO FAIL (conformance signal). Do not hand-edit.

add_standard_compile_fail(lang-4-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/4_conformance/4_error_directive_fails.c)
add_standard_run_test(lang-4-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/4_conformance/4_error_in_skipped_group.c supported)
add_standard_static_assert(lang-4-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/4_conformance/4_freestanding_headers.c supported)
add_standard_run_test(lang-5.1.1.2-08 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.1.2_phase8_external_reference_link.c supported)
add_standard_run_test(lang-5.1.2.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.1_freestanding_startup_calls_main.c supported)
add_standard_run_test(lang-5.1.2.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.1_termination_exit_code.c supported)
add_standard_run_test(lang-5.1.2.2.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.2.1_argv_properties.c deferred)
add_standard_run_test(lang-5.1.2.2.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.2.1_main_argc_argv_form.c)
add_standard_run_test(lang-5.1.2.2.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.2.1_main_void_form.c supported)
add_standard_run_test(lang-5.1.2.2.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.2.3_implicit_return_zero.c supported)
add_standard_run_test(lang-5.1.2.2.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.2.3_return_equals_exit.c supported)
add_standard_stdout_test(lang-5.1.2.3-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.3_line_buffered_output.c ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.3_line_buffered_output.expected supported)
add_standard_stdout_test(lang-5.1.2.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.3_output_flushed_at_exit.c ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.3_output_flushed_at_exit.expected supported)
add_standard_run_test(lang-5.1.2.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.1.2.3_volatile_side_effects_sequenced.c)
add_standard_static_assert(lang-5.2.1.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.1.2_basic_chars_single_byte.c supported)
add_standard_static_assert(lang-5.2.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.1_basic_charset_digits_contiguous.c supported)
add_standard_static_assert(lang-5.2.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.1_execution_charset_values.c supported)
add_standard_static_assert(lang-5.2.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.1_null_character_terminates.c supported)
add_standard_static_assert(lang-5.2.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.2_alphabetic_escapes_control_values.c supported)
add_standard_static_assert(lang-5.2.2-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.2_escape_values_unique.c supported)
add_standard_run_test(lang-5.2.4.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.1_translation_limits_stress.c partial)
add_standard_static_assert(lang-5.2.4.2.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.2.1_char_signedness_limits.c supported)
add_standard_static_assert(lang-5.2.4.2.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.2.1_integer_limit_values_lp64.c supported)
add_standard_static_assert(lang-5.2.4.2.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.2.1_limits_macros_minimums.c supported)
add_standard_static_assert(lang-5.2.4.2.2-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.2.2_float_characteristics_ieee754.c supported)
add_standard_static_assert(lang-5.2.4.2.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.2.2_float_macros_minimums.c supported)
add_standard_static_assert(lang-5.2.4.2.2-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.2.2_flt_rounds_eval_method.c)
add_standard_static_assert(lang-5.2.4.2.2-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/5_environment/5.2.4.2.2_subnormal_support.c)
add_standard_static_assert(lang-6.10.8-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.10.8.3_conditional_feature_macros.c partial)
add_standard_static_assert(lang-6.10.8-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.10.8_stdc_version_macros.c supported)
add_standard_run_test(lang-6.11-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.11_old_style_function_definitions.c supported)
add_standard_run_test(lang-6.6-06 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.6_constant_expressions/6.6_address_constants.c supported)
add_standard_static_assert(lang-6.6-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.6_constant_expressions/6.6_arithmetic_constant_initializers.c supported)
add_standard_compile_fail(lang-6.6-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.6_constant_expressions/6.6_ice_comma_operator.c supported)
add_standard_compile_fail(lang-6.6-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.6_constant_expressions/6.6_ice_float_operand.c supported)
add_standard_compile_fail(lang-6.6-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.6_constant_expressions/6.6_ice_out_of_range.c supported)
add_standard_static_assert(lang-6.6-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.6_constant_expressions/6.6_ice_translation_time.c supported)
add_standard_static_assert(lang-6.6-08 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.6_constant_expressions/6.6_short_circuit_ice.c supported)
add_standard_static_assert(lang-6.7.10-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.10_static_assert_passes.c supported)
add_standard_compile_fail(lang-6.7.1-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.1_block_scope_static_function.c supported)
add_standard_compile_fail(lang-6.7.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.1_multiple_storage_classes.c supported)
add_standard_compile_fail(lang-6.7.1-06 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.1_register_address_of.c supported)
add_standard_run_test(lang-6.7.1-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.1_register_request.c supported)
add_standard_run_test(lang-6.7.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.1_storage_class_specifiers.c)
add_standard_compile_fail(lang-6.7.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.1_thread_local_block_scope.c deferred)
add_standard_run_test(lang-6.7.2.1-09 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_anonymous_struct_union.c supported)
add_standard_compile_fail(lang-6.7.2.1-06 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_bitfield_invalid_type.c supported)
add_standard_run_test(lang-6.7.2.1-08 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_bitfield_layout_lsb_first.c supported)
add_standard_run_test(lang-6.7.2.1-07 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_bitfield_value_semantics.c supported)
add_standard_compile_fail(lang-6.7.2.1-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_bitfield_width_exceeds_type.c supported)
add_standard_run_test(lang-6.7.2.1-11 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_flexible_array_member.c supported)
add_standard_run_test(lang-6.7.2.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_member_address_order.c supported)
add_standard_static_assert(lang-6.7.2.1-10 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_member_natural_alignment.c supported)
add_standard_compile_fail(lang-6.7.2.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_self_containing_struct.c supported)
add_standard_run_test(lang-6.7.2.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_struct_declares_members.c supported)
add_standard_run_test(lang-6.7.2.1-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.1_union_size_and_overlap.c supported)
add_standard_static_assert(lang-6.7.2.2-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.2_enum_compatible_type.c supported)
add_standard_run_test(lang-6.7.2.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.2_enumerator_values.c supported)
add_standard_compile_fail(lang-6.7.2.3-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.3_enum_no_list_before_complete.c supported)
add_standard_run_test(lang-6.7.2.3-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.3_incomplete_tag_forward.c supported)
add_standard_compile_fail(lang-6.7.2.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.3_tag_keyword_mismatch.c supported)
add_standard_run_test(lang-6.7.2.3-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2.3_tag_scoping.c supported)
add_standard_compile_fail(lang-6.7.2-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2_invalid_type_specifier_multiset.c supported)
add_standard_static_assert(lang-6.7.2-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2_plain_int_bitfield_signed.c partial)
add_standard_static_assert(lang-6.7.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.2_type_specifier_multisets.c supported)
add_standard_compile_fail(lang-6.7.3-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.3_const_assignment_target.c supported)
add_standard_compile_fail(lang-6.7.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.3_restrict_non_pointer.c supported)
add_standard_run_test(lang-6.7.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.3_type_qualifiers.c)
add_standard_run_test(lang-6.7.3-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.3_volatile_access.c)
add_standard_run_test(lang-6.7.4-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.4_inline_extern_definition.c supported)
add_standard_run_test(lang-6.7.4-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.4_inline_function.c supported)
add_standard_compile_fail(lang-6.7.4-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.4_inline_static_object.c supported)
add_standard_run_test(lang-6.7.4-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.4_noreturn_function.c supported)
add_standard_compile_fail(lang-6.7.4-08 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.4_specifier_on_main.c supported)
add_standard_compile_fail(lang-6.7.4-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.4_specifier_on_object.c supported)
add_standard_compile_fail(lang-6.7.5-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.5_alignas_invalid_alignment.c supported)
add_standard_compile_fail(lang-6.7.5-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.5_alignas_on_typedef.c supported)
add_standard_static_assert(lang-6.7.5-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.5_alignas_strictest_wins.c supported)
add_standard_run_test(lang-6.7.6.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.1_pointer_declarators.c supported)
add_standard_run_test(lang-6.7.6.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.2_array_declarators.c supported)
add_standard_compile_fail(lang-6.7.6.2-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.2_static_vla.c deferred)
add_standard_compile_fail(lang-6.7.6.2-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.2_zero_size_array.c supported)
add_standard_run_test(lang-6.7.6.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.3_function_prototypes.c supported)
add_standard_compile_fail(lang-6.7.6.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.3_function_returning_array.c supported)
add_standard_run_test(lang-6.7.6.3-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.3_oldstyle_prototype_compat.c supported)
add_standard_run_test(lang-6.7.6.3-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6.3_parameter_adjustment.c supported)
add_standard_run_test(lang-6.7.6-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.6_declarator_binding.c supported)
add_standard_run_test(lang-6.7.7-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.7_type_names_abstract_declarators.c supported)
add_standard_run_test(lang-6.7.8-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.8_typedef_name_shadowing.c supported)
add_standard_run_test(lang-6.7.8-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.8_typedef_synonym.c supported)
add_standard_static_assert(lang-6.7.8-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.8_typedef_underlying_size.c)
add_standard_compile_fail(lang-6.7.8-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.8_typedef_vm_file_scope.c deferred)
add_standard_run_test(lang-6.7.9-10 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_aggregate_brace_lists.c supported)
add_standard_compile_fail(lang-6.7.9-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_block_extern_initializer.c supported)
add_standard_run_test(lang-6.7.9-09 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_char_array_string_literal.c supported)
add_standard_run_test(lang-6.7.9-11 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_designated_initializers.c supported)
add_standard_compile_fail(lang-6.7.9-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_incomplete_type_initializer.c supported)
add_standard_run_test(lang-6.7.9-15 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_initializer_override.c supported)
add_standard_run_test(lang-6.7.9-12 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_partial_initializer_zero_fill.c supported)
add_standard_run_test(lang-6.7.9-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_scalar_initialization.c supported)
add_standard_compile_fail(lang-6.7.9-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_static_nonconstant_initializer.c supported)
add_standard_run_test(lang-6.7.9-06 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_static_zero_initialization.c supported)
add_standard_run_test(lang-6.7.9-08 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_struct_copy_initialization.c supported)
add_standard_run_test(lang-6.7.9-13 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/6.7.9_unknown_size_array_designator.c supported)
add_standard_compile_fail(lang-6.7-05 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/incomplete_no_linkage_object.c supported)
add_standard_compile_fail(lang-6.7-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/no_linkage_redeclared.c supported)
add_standard_run_test(lang-6.7-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.7_declarations/typedef_same_redefinition.c supported)
add_standard_compile_fail(lang-6.8.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.1_duplicate_label_name.c supported)
add_standard_run_test(lang-6.8.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.1_label_is_goto_target.c supported)
add_standard_run_test(lang-6.8.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.2_compound_statement_block.c supported)
add_standard_run_test(lang-6.8.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.3_expression_statement_side_effects.c supported)
add_standard_run_test(lang-6.8.3-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.3_null_statement_noop.c supported)
add_standard_run_test(lang-6.8.4.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.4.1_dangling_else_binds_nearest.c supported)
add_standard_compile_fail(lang-6.8.4.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.4.1_if_controlling_not_scalar.c supported)
add_standard_run_test(lang-6.8.4.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.4.1_if_else_selection.c supported)
add_standard_run_test(lang-6.8.4.2-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.4.2_case_fallthrough.c supported)
add_standard_run_test(lang-6.8.4.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.4.2_switch_case_default_dispatch.c supported)
add_standard_compile_fail(lang-6.8.4.2-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.4.2_switch_controlling_not_integer.c supported)
add_standard_run_test(lang-6.8.5.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.5.1_while_pretest.c supported)
add_standard_run_test(lang-6.8.5.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.5.2_do_posttest.c supported)
add_standard_run_test(lang-6.8.5.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.5.3_for_clauses.c supported)
add_standard_compile_fail(lang-6.8.5-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.5_controlling_expr_nonscalar.c supported)
add_standard_compile_fail(lang-6.8.5-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.5_for_decl_static.c supported)
add_standard_run_test(lang-6.8.6.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.6.1_goto_label.c supported)
add_standard_run_test(lang-6.8.6.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.6.2_continue_loop_continuation.c supported)
add_standard_run_test(lang-6.8.6.3-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.6.3_break_terminates.c supported)
add_standard_run_test(lang-6.8.6.4-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8.6.4_return_converted.c supported)
add_standard_run_test(lang-6.8-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8_block_auto_initializer_on_reach.c supported)
add_standard_run_test(lang-6.8-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.8_statements/6.8_sequence_point_after_full_expression.c supported)
add_standard_compile_fail(lang-6.9-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/auto_register_file_scope.c supported)
add_standard_run_test(lang-6.9.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/file_scope_initialized_definition.c supported)
add_standard_run_test(lang-6.9.1-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/function_definition_executes_body.c supported)
add_standard_run_test(lang-6.9.1-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/prototype_definition_serves_calls.c supported)
add_standard_compile_fail(lang-6.9.2-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/static_tentative_incomplete.c supported)
add_standard_run_test(lang-6.9.2-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/tentative_definitions_collapse.c supported)
add_standard_run_test(lang-6.9.2-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/tentative_incomplete_array.c supported)
add_standard_compile_fail(lang-6.9.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/typedef_function_definition.c supported)
add_standard_compile_fail(lang-6.9.1-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/unnamed_prototype_param_in_definition.c supported)
add_standard_run_test(lang-6.9-03 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.9_external/unused_extern_no_definition.c supported)

# Preprocessor + lexical rows promoted from partial after verifying behavior
# (partial audit 2026-06-23): #error/#if-ICE/_Imaginary rejection,
# #pragma/null-directive/#line acceptance, and __func__.
add_standard_compile_fail(lang-6.10.5-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.10.5_error_directive.c)
add_standard_compile_fail(lang-6.10.1-04 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.10.1_if_requires_ice.c)
add_standard_compile_fail(lang-6.4.1-02 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.4_lexical/6.4.1_imaginary_reserved.c)
add_standard_run_test(lang-6.10.6-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.10.6_pragma_recognized.c)
add_standard_run_test(lang-6.10.7-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.10.7_null_directive.c)
add_standard_run_test(lang-6.10.4-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.10_preprocessing/6.10.4_line_directive.c)
add_standard_stdout_test(lang-6.4.2.2-01 ${CMAKE_CURRENT_SOURCE_DIR}/language/6.4_lexical/6.4.2.2_func_name.c ${CMAKE_CURRENT_SOURCE_DIR}/language/6.4_lexical/6.4.2.2_func_name.expected)
