# Generated — libc (clause 7). Tests assert ISO C17; partial/deferred rows
# EXPECTED TO FAIL (conformance signal). Do not hand-edit.

# A failed assertion must diagnose and abort (non-zero exit), which a plain
# exit-0 run test cannot express — use the abort-expecting harness.
add_standard_run_abort_test(libc-assert-assert-abort ${CMAKE_CURRENT_SOURCE_DIR}/libc/assert/assert_abort.c supported)
add_standard_stderr_test(libc-assert-assert-diag ${CMAKE_CURRENT_SOURCE_DIR}/libc/assert/assert_diag.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/assert/assert_diag.expected supported)
add_standard_run_test(libc-assert-assert-nonzero ${CMAKE_CURRENT_SOURCE_DIR}/libc/assert/assert_nonzero.c supported)
add_standard_run_test(libc-assert-ndebug ${CMAKE_CURRENT_SOURCE_DIR}/libc/assert/ndebug.c supported)
add_standard_static_assert(libc-assert-static-assert ${CMAKE_CURRENT_SOURCE_DIR}/libc/assert/static_assert.c supported)
add_standard_run_test(libc-ctype-isblank ${CMAKE_CURRENT_SOURCE_DIR}/libc/ctype/isblank.c supported)
add_standard_run_test(libc-errno-errno ${CMAKE_CURRENT_SOURCE_DIR}/libc/errno/errno_lvalue.c supported)
add_standard_run_test(libc-errno-set ${CMAKE_CURRENT_SOURCE_DIR}/libc/errno/errno_set.c supported)
add_standard_static_assert(libc-errno-edom ${CMAKE_CURRENT_SOURCE_DIR}/libc/errno/error_macros.c supported)
add_standard_static_assert(libc-float-decimal_dig ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/decimal_dig.c supported)
add_standard_static_assert(libc-float-flt_dig ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_dig.c supported)
add_standard_static_assert(libc-float-flt_epsilon ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_epsilon.c supported)
add_standard_static_assert(libc-float-flt_eval_method ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_eval_method.c supported)
add_standard_static_assert(libc-float-flt_has_subnorm ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_has_subnorm.c)
add_standard_static_assert(libc-float-flt_mant_dig ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_mant_dig.c supported)
add_standard_static_assert(libc-float-flt_max ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_max.c supported)
add_standard_static_assert(libc-float-flt_min ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_min.c supported)
add_standard_static_assert(libc-float-flt_min_10_exp ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_min_10_exp.c supported)
add_standard_static_assert(libc-float-flt_min_exp ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_min_exp.c supported)
add_standard_static_assert(libc-float-flt_radix ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_radix.c supported)
add_standard_static_assert(libc-float-flt_rounds ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_rounds.c)
add_standard_static_assert(libc-float-flt_true_min ${CMAKE_CURRENT_SOURCE_DIR}/libc/float/flt_true_min.c supported)
add_standard_run_test(libc-inttypes-imaxabs ${CMAKE_CURRENT_SOURCE_DIR}/libc/inttypes/imaxabs.c supported)
add_standard_static_assert(libc-inttypes-imaxdiv_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/inttypes/imaxdiv_t.c supported)
add_standard_static_assert(libc-inttypes-pri-macros ${CMAKE_CURRENT_SOURCE_DIR}/libc/inttypes/pri_macros.c supported)
add_standard_static_assert(libc-inttypes-scn-macros ${CMAKE_CURRENT_SOURCE_DIR}/libc/inttypes/scn_macros.c)
add_standard_run_test(libc-inttypes-strtoimax ${CMAKE_CURRENT_SOURCE_DIR}/libc/inttypes/strtoimax.c supported)
add_standard_static_assert(libc-iso646-and ${CMAKE_CURRENT_SOURCE_DIR}/libc/iso646/alternative_spellings.c deferred)
add_standard_static_assert(libc-locale-lconv ${CMAKE_CURRENT_SOURCE_DIR}/libc/locale/lconv.c supported)
add_standard_run_test(libc-locale-localeconv ${CMAKE_CURRENT_SOURCE_DIR}/libc/locale/localeconv.c supported)
add_standard_run_test(libc-locale-setlocale ${CMAKE_CURRENT_SOURCE_DIR}/libc/locale/setlocale.c supported)
add_standard_run_test(libc-math-compare ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/compare.c supported)
add_standard_static_assert(libc-math-errhandling ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/errhandling.c supported)
add_standard_run_test(libc-math-exp ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/exp.c supported)
add_standard_run_test(libc-math-fma ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/fma.c supported)
add_standard_run_test(libc-math-fmax ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/fmax.c supported)
add_standard_run_test(libc-math-fmod ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/fmod.c supported)
add_standard_static_assert(libc-math-fp_classes ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/fp_classes.c supported)
add_standard_run_test(libc-math-fpclassify ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/fpclassify.c supported)
add_standard_run_test(libc-math-huge_val ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/huge_val.c supported)
add_standard_run_test(libc-math-hyper ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/hyper.c supported)
add_standard_run_test(libc-math-isfinite ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/isfinite.c supported)
add_standard_run_test(libc-math-isinf ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/isinf.c supported)
add_standard_run_test(libc-math-isnan ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/isnan.c supported)
add_standard_run_test(libc-math-isnormal ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/isnormal.c supported)
add_standard_run_test(libc-math-manip ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/manip.c supported)
add_standard_run_test(libc-math-pow ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/pow.c supported)
add_standard_run_test(libc-math-round ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/round.c supported)
add_standard_run_test(libc-math-signbit ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/signbit.c supported)
add_standard_run_test(libc-math-trig ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/trig.c supported)
add_standard_static_assert(libc-math-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/math/types.c supported)
add_standard_static_assert(libc-signal-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/signal/types.c supported)
add_standard_static_assert(libc-stdalign-alignas ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdalign/alignas.c deferred)
add_standard_static_assert(libc-stdalign-alignof ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdalign/alignof.c deferred)
add_standard_static_assert(libc-stdalign-defined ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdalign/defined.c deferred)
add_standard_run_test(libc-stdarg-va_arg ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdarg/va_arg.c)
add_standard_run_test(libc-stdarg-va_copy ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdarg/va_copy.c)
add_standard_run_test(libc-stdarg-va_end ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdarg/va_end.c)
add_standard_run_test(libc-stdarg-va_list ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdarg/va_list.c)
add_standard_run_test(libc-stdarg-va_start ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdarg/va_start.c)
add_standard_static_assert(libc-stdbool-bool ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdbool_extra/bool_macro.c supported)
add_standard_static_assert(libc-stddef-max_align_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stddef/max_align_t.c supported)
add_standard_run_test(libc-stddef-null ${CMAKE_CURRENT_SOURCE_DIR}/libc/stddef/null.c supported)
add_standard_run_test(libc-stddef-offsetof ${CMAKE_CURRENT_SOURCE_DIR}/libc/stddef/offsetof.c supported)
add_standard_static_assert(libc-stddef-ptrdiff_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stddef/ptrdiff_t.c supported)
add_standard_static_assert(libc-stddef-size_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stddef/size_t.c supported)
add_standard_static_assert(libc-stddef-wchar_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stddef/wchar_t.c)
add_standard_static_assert(libc-stdint-int_fastn_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdint_extra/int_fastn_t.c supported)
add_standard_static_assert(libc-stdint-int_leastn_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdint_extra/int_leastn_t.c supported)
add_standard_static_assert(libc-stdint-intmax_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdint_extra/intmax_t.c supported)
add_standard_static_assert(libc-stdint-intn_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdint_extra/intn_t.c supported)
add_standard_static_assert(libc-stdint-intptr_t ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdint_extra/intptr_t.c supported)
add_standard_run_test(libc-stdio-fclose ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fclose.c supported)
add_standard_stdout_test(libc-stdio-fflush ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fflush.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fflush.expected supported)
add_standard_run_test(libc-stdio-fgetc ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fgetc.c supported)
add_standard_run_test(libc-stdio-fgets ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fgets.c supported)
add_standard_static_assert(libc-stdio-file-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/file_types.c supported)
add_standard_stdout_test(libc-stdio-flush-at-exit ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/flush_at_exit.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/flush_at_exit.expected supported)
add_standard_run_test(libc-stdio-fopen ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fopen.c supported)
add_standard_stdout_test(libc-stdio-fprintf ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fprintf.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fprintf.expected supported)
add_standard_run_test(libc-stdio-fread ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fread.c supported)
add_standard_run_test(libc-stdio-freopen ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/freopen.c supported)
add_standard_run_test(libc-stdio-fseek ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fseek.c supported)
add_standard_run_test(libc-stdio-fwrite ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/fwrite.c supported)
add_standard_static_assert(libc-stdio-macros ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/macros.c supported)
add_standard_stdout_test(libc-stdio-printf-float ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/printf_float.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/printf_float.expected supported)
add_standard_stdout_test(libc-stdio-printf ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/printf_return.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/printf_return.expected supported)
add_standard_run_test(libc-stdio-remove-rename ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/remove_rename.c supported)
add_standard_stdout_test(libc-stdio-setvbuf ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/setvbuf.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/setvbuf.expected supported)
add_standard_run_test(libc-stdio-snprintf ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/snprintf.c supported)
add_standard_run_test(libc-stdio-sprintf ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/sprintf.c supported)
add_standard_run_test(libc-stdio-stream-error ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/stream_error.c supported)
add_standard_stdout_test(libc-stdio-streams ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/streams.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/streams.expected supported)
add_standard_stdout_test(libc-stdio-vprintf ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/vprintf.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdio/vprintf.expected supported)
add_standard_run_test(libc-stdlib-uppercase-exit ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/_exit.c supported)
add_standard_run_abort_test(libc-stdlib-abort ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/abort.c supported)
add_standard_run_test(libc-stdlib-abs ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/abs.c supported)
add_standard_run_test(libc-stdlib-aligned-alloc ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/aligned_alloc.c supported)
add_standard_stdout_test(libc-stdlib-atexit ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/atexit.c ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/atexit.expected supported)
add_standard_run_test(libc-stdlib-atof ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/atof.c supported)
add_standard_run_test(libc-stdlib-atoi ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/atoi.c supported)
add_standard_run_test(libc-stdlib-bsearch ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/bsearch.c supported)
add_standard_run_test(libc-stdlib-calloc ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/calloc.c supported)
add_standard_run_test(libc-stdlib-div ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/div.c supported)
add_standard_run_test(libc-stdlib-exit ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/exit.c supported)
add_standard_run_test(libc-stdlib-free ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/free.c supported)
add_standard_run_test(libc-stdlib-getenv ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/getenv.c supported)
add_standard_static_assert(libc-stdlib-macros ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/macros.c supported)
add_standard_run_test(libc-stdlib-malloc ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/malloc.c supported)
add_standard_run_test(libc-stdlib-mb ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/mb.c supported)
add_standard_run_test(libc-stdlib-qsort ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/qsort.c supported)
add_standard_run_test(libc-stdlib-quick-exit ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/quick_exit.c supported)
add_standard_run_test(libc-stdlib-rand ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/rand.c supported)
add_standard_run_test(libc-stdlib-realloc ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/realloc.c supported)
add_standard_run_test(libc-stdlib-strtod ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/strtod.c supported)
add_standard_run_test(libc-stdlib-strtol ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/strtol.c)
add_standard_static_assert(libc-stdlib-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdlib/types.c supported)
add_standard_run_test(libc-stdnoreturn-noreturn ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdnoreturn/noreturn.c deferred)
add_standard_run_test(libc-string-memchr ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/memchr.c supported)
add_standard_run_test(libc-string-memcmp ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/memcmp.c supported)
add_standard_run_test(libc-string-memcpy ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/memcpy.c supported)
add_standard_run_test(libc-string-memmove ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/memmove.c supported)
add_standard_run_test(libc-string-memset ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/memset.c supported)
add_standard_run_test(libc-string-strcat ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strcat.c supported)
add_standard_run_test(libc-string-strchr ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strchr.c supported)
add_standard_run_test(libc-string-strcoll ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strcoll.c supported)
add_standard_run_test(libc-string-strcpy ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strcpy.c supported)
add_standard_run_test(libc-string-strcspn ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strcspn.c supported)
add_standard_run_test(libc-string-strerror ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strerror.c supported)
add_standard_run_test(libc-string-strncat ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strncat.c supported)
add_standard_run_test(libc-string-strncmp ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strncmp.c supported)
add_standard_run_test(libc-string-strncpy ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strncpy.c supported)
add_standard_run_test(libc-string-strpbrk ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strpbrk.c supported)
add_standard_run_test(libc-string-strrchr ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strrchr.c supported)
add_standard_run_test(libc-string-strspn ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strspn.c supported)
add_standard_run_test(libc-string-strstr ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strstr.c supported)
add_standard_run_test(libc-string-strtok ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strtok.c supported)
add_standard_run_test(libc-string-strxfrm ${CMAKE_CURRENT_SOURCE_DIR}/libc/string/strxfrm.c supported)
add_standard_run_test(libc-time-asctime ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/asctime.c supported)
add_standard_run_test(libc-time-clock ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/clock.c supported)
add_standard_run_test(libc-time-difftime ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/difftime.c supported)
add_standard_run_test(libc-time-gmtime ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/gmtime.c supported)
add_standard_static_assert(libc-time-macros ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/macros.c supported)
add_standard_run_test(libc-time-mktime ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/mktime.c supported)
add_standard_run_test(libc-time-strftime ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/strftime.c supported)
add_standard_run_test(libc-time-time ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/time.c supported)
add_standard_run_test(libc-time-timespec_get ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/timespec_get.c supported)
add_standard_static_assert(libc-time-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/time/types.c supported)
add_standard_static_assert(libc-uchar-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/uchar/types.c supported)
add_standard_static_assert(libc-wchar-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/wchar/types.c supported)
add_standard_static_assert(libc-wctype-types ${CMAKE_CURRENT_SOURCE_DIR}/libc/wctype/types.c supported)

# Promoted from partial after verifying behavior (partial audit 2026-06-23):
# stdint "other" limit macros (#81 now lets sizeof/limits evaluate in a
# _Static_assert). (printf-flags was already registered above.)
add_standard_static_assert(libc-stdint-other-limits ${CMAKE_CURRENT_SOURCE_DIR}/libc/stdint_extra/other_limits.c)
